apiVersion: v1
data:
  alertmanager.yml: |
    global: null
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"alertmanager.yml":"global: null\nreceivers:\n- name: default-receiver\nroute:\n  group_interval: 5m\n  group_wait: 10s\n  receiver: default-receiver\n  repeat_interval: 3h\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"alertmanager","app.kubernetes.io/name":"prometheus"},"name":"prometheus-alertmanager-config","namespace":"prometheus","ownerReferences":[{"apiVersion":"app.k8s.io/v1beta1","blockOwnerDeletion":true,"kind":"Application","name":"prometheus","uid":"36962a95-2521-4e53-a23d-03b7b160ef5e"}]}}
  creationTimestamp: "2023-03-03T11:18:49Z"
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/name: prometheus
  name: prometheus-alertmanager-config
  namespace: prometheus
  ownerReferences:
  - apiVersion: app.k8s.io/v1beta1
    blockOwnerDeletion: true
    kind: Application
    name: prometheus
    uid: 36962a95-2521-4e53-a23d-03b7b160ef5e
  resourceVersion: "94372"
  uid: 14a3df8e-5b6b-4429-bdb9-d9cc65f9eebf
