apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"alertmanager","app.kubernetes.io/name":"prometheus","k8s-app":"alertmanager"},"name":"prometheus-alertmanager","namespace":"prometheus","ownerReferences":[{"apiVersion":"app.k8s.io/v1beta1","blockOwnerDeletion":true,"kind":"Application","name":"prometheus","uid":"36962a95-2521-4e53-a23d-03b7b160ef5e"}]},"spec":{"ports":[{"name":"http","port":9093,"protocol":"TCP","targetPort":9093}],"selector":{"k8s-app":"alertmanager"},"type":"ClusterIP"}}
  creationTimestamp: "2023-03-03T11:18:49Z"
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/name: prometheus
    k8s-app: alertmanager
  name: prometheus-alertmanager
  namespace: prometheus
  ownerReferences:
  - apiVersion: app.k8s.io/v1beta1
    blockOwnerDeletion: true
    kind: Application
    name: prometheus
    uid: 36962a95-2521-4e53-a23d-03b7b160ef5e
  resourceVersion: "94379"
  uid: 083afe6f-7c35-4071-b084-4acebf46b3b3
spec:
  clusterIP: 10.3.246.196
  clusterIPs:
  - 10.3.246.196
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    k8s-app: alertmanager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
